console.log("Value of PI " + Math.PI)
console.log("Value of Euler number " + Math.E)
console.log("Value of after round " + Math.round(Math.PI))
console.log("Value of after .5 round " + Math.round(Math.E))
console.log("Lowest Value " + Math.ceil(3.4))
console.log("Heighest Value " + Math.floor(3.8))
console.log("Value after removing digits after decimal " +Math.trunc(4.5678765))
console.log("Value after power " + Math.pow(2,3))
console.log("Value of sqrt " + Math.sqrt(100))
console.log("Find minimum " + Math.pow(2,3))